# Generated by Django 3.0.4 on 2020-04-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200316_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_canvas_call', models.DateTimeField()),
            ],
        ),
    ]
