# Generated by Django 3.0.4 on 2020-04-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='last_canvas_call',
            field=models.DateTimeField(null=True),
        ),
    ]
